-- MySQL Script generated by MySQL Workbench
-- Sab 24 Mar 2018 11:44:41  WIB
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `id` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NULL,
  `name` VARCHAR(255) NULL,
  `username` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`devices`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`devices` (
  `id` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NULL,
  `type` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`subscribe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`subscribe` (
  `users_id` VARCHAR(255) NOT NULL,
  `devices_id` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`users_id`, `devices_id`),
  INDEX `fk_users_has_devices_devices1_idx` (`devices_id` ASC),
  INDEX `fk_users_has_devices_users_idx` (`users_id` ASC),
  CONSTRAINT `fk_users_has_devices_users`
    FOREIGN KEY (`users_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_devices_devices1`
    FOREIGN KEY (`devices_id`)
    REFERENCES `mydb`.`devices` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
